name: CI
on: [ push, pull_request ]
jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
    - name: Jest Coverage
      uses: mattallty/jest-github-action@v1
      continue-on-error: true
      with:
        changes-only: true
        test-command: 'yarn test:coverage'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
